source/SDNweb/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SDNweb.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

source/SDNweb/Pages/GetTopo.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Globalization;
using System.Net;
using System.Reflection.Metadata.Ecma335;
using System.IO;
using Newtonsoft.Json.Linq;

namespace SDNweb.Pages
{
    public class GetTopoModel : PageModel
    {
        private readonly ILogger<GetTopoModel> _logger;

        public GetTopoModel(ILogger<GetTopoModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            string dateTime = DateTime.Now.ToString("d", new CultureInfo("en-US"));
            ViewData["TimeStamp"] = dateTime;
        }

        public void OnPostGetData()
        {
            String hosts = GetONOSInformation("hosts");
            String Devices = GetONOSInformation("devices");
            String Links = GetONOSInformation("links");
            String Deviceids = DevicestoDevicesid(Devices);

            ViewData["Devices"] = Devices;
            ViewData["Hosts"] = hosts;
            ViewData["Links"] = Links;
            ViewData["Deviceids"] = Deviceids;


            string dateTime = DateTime.Now.ToString("d", new CultureInfo("en-US"));
            ViewData["TimeStamp"] = dateTime;

            ViewData["Test"] = "OnPostGetTopo execute complete";
        }

        public String GetONOSInformation(String getItem)
        {
            HttpClientHandler httpClientHandler = new HttpClientHandler()
            {
                Credentials = new NetworkCredential("onos", "rocks"),
            };

            using (var client = new HttpClient(httpClientHandler))
            {
                var endpoint = new Uri("http://192.168.98.142:8181/onos/v1/" + getItem);
                var result = client.GetAsync(endpoint).Result;
                var jsonstring = result.Content.ReadAsStringAsync().Result;
                return jsonstring;
            }
        }

        public String DevicestoDevicesid(String devices)
        {
            List<string> deviceids = new List<string>();

            foreach (var item in devices.Replace("}{", "}|{").Split('|'))
            {
                String line = item;
                //Console.WriteLine(line);

                dynamic dline = JObject.Parse(line);
                String device = Convert.ToString(dline.devices[0]);
                dynamic ddevice = JObject.Parse(device);
                //Console.WriteLine("test:" + ddevice.id);
                String deviceid = Convert.ToString(ddevice.id);
                deviceids.Add(deviceid);
            }


            var result = String.Join(", ", deviceids.ToArray());
            return result;
        }


    }
}

source/SDNweb/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SDNweb.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

source/SDNweb/Pages/PostTest.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Hosting;
using System.Collections.Specialized;
using System.Globalization;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading;
using static System.Net.WebRequestMethods;
using System.Text.Json.Serialization;
using System.Linq;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Text.Json.Nodes;


namespace SDNweb.Pages
{
    public class PostTestModel : PageModel
    {
       
        private readonly ILogger<PostTestModel> _logger;

        public PostTestModel(ILogger<PostTestModel> logger)
        {
            _logger = logger;
        }

        public class Criterion
        {
            public string type { get; set; }
            public string ethType { get; set; }
            public string ip { get; set; }
        }
        public class Instructions
        {
            public string type { get; set; }            
            public int port { get; set; }
        }

        public void OnGet()
        {           
           string dateTime = DateTime.Now.ToString("d", new CultureInfo("en-US"));
           ViewData["TimeStamp"] = dateTime;
        }

        public void OnPostPostTest(string WebIP,string deviceID, string appID, string stream)
        {            
            string dateTime = DateTime.Now.ToString("d", new CultureInfo("en-US"));            
            ViewData["TimeStamp"] = dateTime;
            POSTONOSInformation("d");
        }

        public async void POSTONOSInformation(String getItem)
        {
            List<string> deferred_ID = new List<string>() { };
            List<Instructions> instructionsID = new List<Instructions>()
            {
                new Instructions(){type = "OUTPUT",port=1}                
            };            

            List<Criterion> criteria_ID = new List<Criterion>() 
            {
                new Criterion(){type = "ETH_TYPE",ethType = "0x0800"},
                new Criterion(){type = "IPV4_DST",ip = "10.0.0.1/32"}
            };
            var senddata = new
            {
                priority = 4001,
                timeout = 0,
                isPermanent = true,
                deviceId = "of:0000000000000001",
                treatment = new
                {
                    deferred = deferred_ID,
                    instructions = instructionsID
                },
                selector = new
                {
                    criteria = criteria_ID

                }
            };

            HttpClientHandler httpClientHandler = new HttpClientHandler()
            {
                Credentials = new NetworkCredential("onos", "rocks"),
            };

            var json = JsonConvert.SerializeObject(senddata);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var url = "http://192.168.98.142:8181/onos/v1/flows/of%3A0000000000000001?appId=hello";            
            using var client = new HttpClient(httpClientHandler);
            var response = await client.PostAsync(url, data);
            string result = response.Content.ReadAsStringAsync().Result;
            
            
            Console.WriteLine(url);
            //Console.WriteLine(result);
        }
    }
}

source/SDNweb/Pages/Redirect.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SDNweb.Pages
{
    public class RedirectModel : PageModel
    {
        public void OnGet()
        {
           //Response.write("<script>window.open(newpage.aspx;_blank;)</script>");
        }
    }
}

source/SDNweb/Pages/GetTopo.cshtml
@page
@model GetTopoModel
@{
    ViewData["Title"] = "ONOS Get Topo Page";
}

<h1>@ViewData["Title"]</h1>
<p>This page is under construction as of @ViewData["Timestamp"]</p>
<br>

<form method="POST">
    <button type="submit" asp-page-handler="GetData" class="btn btn-primary">
        GetTopo
    </button>
</form>
<br />

<p>
    <h3>GetTopo test</h3>
    @ViewData["Test"]
    <h3>Devices</h3>
    @ViewData["Devices"]
    <h3>Hosts</h3>
    @ViewData["Hosts"]
    <h3>Links</h3>
    @ViewData["Links"]
    <h3>Deviceids</h3>
    @ViewData["Deviceids"]
</p>

source/SDNweb/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Hello World</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

source/SDNweb/Pages/PostTest.cshtml
@page
@model SDNweb.Pages.PostTestModel
@{
	ViewData["Title"] = "ONOS Post Test Page";
}

<h1>@ViewData["Title"]</h1>
<p>This page is under construction as of @ViewData["Timestamp"]</p>
<br>

<form method="POST">    
    web ip<input class="form-control" id="WebIP" name="WebIP" type="text" />    
    deviceID<input class="form-control" id="deviceID" name="deviceID" type="text" />       
    appID<input class="form-control" id="appID" name="appID" type="text" />       
    <br>
    <button type="submit" asp-page-handler="PostTest" class="btn btn-primary">
        Post
    </button>


</form>
<body>
    
</body>

<br />

<p>
    <h2>PostTest test</h2>
    <p>textbox</p>
    @ViewData["textbox"]
    <br>    


</p>

source/SDNweb/Pages/Redirect.cshtml
@page
@model SDNweb.Pages.RedirectModel
@{
    ViewData["Title"] = "Redirct";
}
<h1>@ViewData["Title"]</h1>

<a href="https://www.google.com" target="_blank">google</a>

source/SDNweb/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SDNweb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SDNweb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">SDNweb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/GetTopo">GetTopo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/PostTest">PostTest</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Redirect">Redirect</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SDNweb - <a asp-area="" asp-page="/GetTopo">GetTopo</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>